from pytube import YouTube
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound

from utils.loghelper import MyLogger
from models.model import URL


logger = MyLogger.__call__().get_logger()


def yt_subtitle_fetcher(link: str, lang="en"):
    logger.info(msg="FN_CALL with paramerters [link:{}, lang:{}]".format(link, lang))
    video_id = link.split("v=")[1]
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id=video_id)

        # filter for manually created transcripts
        try:
            m_transcript = transcript_list.find_manually_created_transcript([lang])
            return True, subtitle_parser(m_transcript.fetch())
        except NoTranscriptFound:
            logger.warn("No transcript found for lang {}".format(lang))

            # or automatically generated ones
            try:
                auto_transcript = transcript_list.find_generated_transcript([lang])
                return True, subtitle_parser(auto_transcript.fetch())
            except NoTranscriptFound:
                logger.warn(
                    "No autogenerated transcript found for lang {}".format(lang)
                )
                return False, None

    except TranscriptsDisabled:
        logger.warn("No transcript found for lang {}".format(lang))
        return False, None


def subtitle_parser(subtitle):
    transcript = []
    for item in subtitle:
        transcript.append(item["text"])
    return transcript
